name: Auto Login and Email Result

on:
  schedule:
    - cron: "0 0 */60 * *"
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install playwright
          playwright install

      - name: Run login script
        env:
          USERNAME1: ${{ secrets.USERNAME1 }}
          PASSWORD1: ${{ secrets.PASSWORD1 }}
          PANEL_INDEX1: ${{ secrets.PANEL_INDEX1 }}
          USERNAME2: ${{ secrets.USERNAME2 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
          PANEL_INDEX2: ${{ secrets.PANEL_INDEX2 }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python script.py
